my project/config/routes.rb
require File.expand_path("../../lib/routes_constraints", __FILE__)


MuddleMe::Application.routes.draw do
  
  namespace :admins do resources :store_categories end
  namespace :admins do resources :product_categories end
   
  # ======== mm box web app routes =============
  get '/google_search' => 'search#google_search', :as => :google_search
  get '/mm_box_search' => 'search#search'
  get '/mm_prompt_cc_window' => 'search#prompt_cc_window'
  post '/hp_mm_box_merchants_search' => 'search#hp_merchants_search'
  get '/hp_pc_merchants' => 'search#hp_pc_merchants'
  get '/hp_mm_box_services_search' => 'search#hp_services_search'
  get '/mm_zip_code_window' => 'search#prompt_zipcode_window'
  get '/mm_box_search_lite' => 'search#search_lite'
  get '/mm_affiliate_merchants_search' => 'search#affiliate_search'
  get '/mm_box_get_current_user' => 'search#get_current_user'
  post '/mm_activate_merchant' => 'search#activate_merchant'
  get '/mm_extension_background_iframe' => 'search#extension_background_iframe'
  get '/mm_box_get_user_messages' => 'search#get_user_messages'
  post '/mm_box_remove_user_message' => 'search#remove_user_message'
  post '/mm_skip_info_before_shopping' => 'search#skip_info_before_shopping'
  get '/mm_check_coupons_by_location' => 'search#check_coupons_by_location'
  get '/muddleme-search' =>'search#muddleme_search'

  # ========= bing search ===================
  get '/bing_search' => 'search#bing_search'

  # utils
  get '/rtest' => 'search#rtest'
  post '/rtest' => 'search#rtest'
  post '/rupload' => 'search#rupload'

  # tmp
  get '/linkshare_mapping' => 'search#linkshare_mapping'
  get '/cj_mapping' => 'search#cj_mapping'
  get '/avant_mapping' => 'search#avant_mapping'
  get '/pj_mapping' => 'search#pj_mapping'
  get '/mm_soleo_number_clicks_report' => 'search#mm_soleo_number_clicks_report'

  # extensions
  get '/mm-extension' => 'application#mm_extension'
  get '/mm-extension-lite' => 'application#mm_extension_lite'
  get '/mm-ie-extension' => 'application#mm_ie_extension'
  get '/mm-firefox-extension' => 'application#mm_firefox_extension'
  get '/mm-chrome-extension' => 'application#mm_chrome_extension'

  get '/safari-extension.safariextz' => 'application#mm_safari_extension'
  get '/safari-extension-lite.safariextz' => 'application#mm_safari_extension_lite'
  get '/safari-extension.plist' => 'application#mm_safari_extension_plist'

  get '/enable-ie' => 'application#enable_ie'
  get '/enable-safari' => 'application#enable_safari'
  get '/search/autocomplete_muddleme_search' => "search#autocomplete_muddleme_search"
  get '/search/autocomplete_service_search' => "search#autocomplete_service_search"

  # ======== mm box web app routes =============
  # ======== backend routes =============
  get '/search_requests' => 'users/search_requests#index', :constraints => LoggedInUserConstraint.new
  get '/search_requests/:id' => 'users/search_requests#show', :constraints => LoggedInUserConstraint.new
  get '/search_requests/:id/outcome' => 'users/search_requests#outcome', :constraints => LoggedInUserConstraint.new
  post '/search_requests/:id/update_outcome' => 'users/search_requests#update_outcome', :constraints => LoggedInUserConstraint.new
  # ======== backend routes =============

  match '/api/auth/facebook/callback' => 'users/api_omniauth_callbacks#facebook'
  match '/api/auth/twitter/callback' => 'users/api_omniauth_callbacks#twitter'
  match '/api/auth/google_oauth2/callback' => 'users/api_omniauth_callbacks#google_oauth2'

  mount Api => "/api"

  root :to => "users#dashboard", :constraints => LoggedInUserConstraint.new
  root :to => "vendors#dashboard", :constraints => LoggedInVendorConstraint.new
  root :to => "admins/finance#index", :constraints => LoggedInAdminConstraint.new

  root :to => 'application#index'
  get '/experience' => 'application#experience'
  get '/referral' => 'application#referral'
  post '/hp_user_sign_up' => 'users#hp_user_sign_up'
  post '/check_subscriber_email' => 'users#check_subscriber_email'
  get '/hp_direct_sign_up' => 'users#hp_direct_sign_up'
  post '/send_sms' => 'users#send_sms_to_users'
  get '/load_more_posts' => 'users#load_more_posts'

  devise_for :users, :controllers => {
    :sessions => "users/devise/sessions",
    :passwords => "users/devise/passwords",
    :registrations => "users/devise/registrations",
    :confirmations => "users/devise/confirmations",
    :unlocks => "users/devise/unlocks",
    :omniauth_callbacks => "users/devise/omniauth_callbacks"
  },
    :skip=>[:sessions, :passwords, :confirmations] do
    get     '/login'   => 'users/devise/sessions#new', :as => "new_user_session"
    post    '/login'   => 'users/devise/sessions#create', :as => "user_session"
    delete  '/logout'  => 'users/devise/sessions#destroy', :as => "destroy_user_session"
    post    '/reset/send'   => 'users/devise/passwords#create', :as => "user_password"
    get     '/reset/send'   => 'users/devise/passwords#new', :as => "new_user_password"
    get     '/reset'        => 'users/devise/passwords#edit', :as => "edit_user_password"
    put     '/reset'        => 'users/devise/passwords#update', :as => "update_user_password"
    get     '/signup'  => 'users/devise/registrations#new', :as => "new_user_registration"
    post    '/signup'  => 'users/devise/registrations#new', :as => "new_user_registration"
    post    '/signup/create'  => 'users/devise/registrations#create', :as => 'user_registration'
    get     '/confirm' => 'users/devise/confirmations#show', :as => "user_confirmation"
    get     '/confirm_new' => 'users/devise/confirmations#new', :as => "new_user_confirmation"
    post    '/confirm' => 'users/devise/confirmations#create', :as => "user_confirmation"
  end

  devise_for :vendors ,
    :controllers => {
    :sessions => "vendors/devise/sessions",
    :passwords => "vendors/devise/passwords",
    :registrations => "vendors/devise/registrations",
    :confirmations => "vendors/devise/confirmations",
    :unlocks => "vendors/devise/unlocks",
  },
    :skip=>[:sessions, :passwords, :confirmations] do
    get     '/company/login'   => 'vendors/devise/sessions#new', :as => "new_vendor_session"
    post    '/company/login'   => 'vendors/devise/sessions#create', :as => "vendor_session"
    delete  '/company/logout'  => 'vendors/devise/sessions#destroy', :as => "destroy_vendor_session"
    post    '/company/reset/send'   => 'vendors/devise/passwords#create', :as => "vendor_password"
    get     '/company/reset/send'   => 'vendors/devise/passwords#new', :as => "new_vendor_password"
    get     '/company/reset'        => 'vendors/devise/passwords#edit', :as => "edit_vendor_password"
    put     '/company/reset'        => 'vendors/devise/passwords#update', :as => "update_vendor_password"
    get     '/company/signup_original'  => 'vendors/devise/registrations#original', :as => "new_vendor_registration"
    get     '/company/signup_premium'  => 'vendors/devise/registrations#premium', :as => "new_vendor_registration"
    get     '/company/signup'  => 'vendors/devise/registrations#new', :as => "new_vendor_registration"
    post    '/company/signup'  => 'vendors/devise/registrations#new', :as => "new_vendor_registration"
    get     '/company/signup/step1'  => 'vendors/devise/registrations#step1', :as => "step1_vendor_registration"
    post    '/company/signup/step1'  => 'vendors/devise/registrations#step1', :as => "step1_vendor_registration"
    get     '/company/signup/step2' => 'vendors/devise/registrations#step2', :as => "step2_vendor_registration"
    post    '/company/signup/step2' => 'vendors/devise/registrations#step2', :as => "step2_vendor_registration"
    post    '/company/signup/create'  => 'vendors/devise/registrations#create', :as => 'vendor_registration'
    get     '/company/confirm' => 'vendors/devise/confirmations#show', :as => "vendor_confirmation"
    get     '/company/confirm_new' => 'vendors/devise/confirmations#new', :as => "new_vendor_confirmation"
    post    '/company/confirm' => 'vendors/devise/confirmations#create', :as => "vendor_confirmation"
  end

  devise_for :admins,
    :controllers => {
    :sessions => "admins/devise/sessions",
    :passwords => "admins/devise/passwords",
  },
    :skip=>[:sessions, :passwords] do
    get     '/admin'   => 'admins/devise/sessions#new', :as => "new_admin_session"
    post    '/admin'   => 'admins/devise/sessions#create', :as => "admin_session"
    delete  '/admin/logout'  => 'admins/devise/sessions#destroy', :as => "destroy_admin_session"
    post    '/admin/reset/send'   => 'admins/devise/passwords#create', :as => "admin_password"
    get     '/admin/reset/send'   => 'admins/devise/passwords#new', :as => "new_admin_password"
    get     '/admin/reset'        => 'admins/devise/passwords#edit', :as => "edit_admin_password"
    put     '/admin/reset'        => 'admins/devise/passwords#update', :as => "update_admin_password"
  end

  match '/contact' => 'contact_messages#new', :as => 'contact', :via => :get
  match '/contact' => 'contact_messages#create', :as => 'contact', :via => :post

  match '/what_is_muddle_me', :to=>'users#what_is_muddle_me'
  match '/what_is_it', :to=>'users#what_is_muddle_me'
  match '/about', :to=>'users#what_is_muddle_me'
  match '/how_it_works', :to=>'users#how_it_works'
  match '/terms_and_conditions', :to => 'users#terms_and_conditions'
  match '/privacy_policy', :to => 'users#privacy_policy'
  match '/faq', :to => 'users#faq'
  match '/UC', :to => 'users#university'
  match '/uc', :to => 'users#university'
  match '/IAC', :to => 'users#iac'
  match '/iac', :to => 'users#iac'


  match "/company", :to => "vendors#dashboard", :as=>'company', :constraints => LoggedInVendorConstraint.new
  match "/company", :to => "vendors#index", :as=>'company'

  match '/company/what_is_muddle_me', :to=>'vendors#what_is_muddle_me'
  match '/company/what_is_it', :to=>'vendors#what_is_muddle_me'
  match '/company/about', :to=>'vendors#what_is_muddle_me'

my project/app/views/admins/_sub_nav.html.haml
- active_action ||= ''
- active_controller ||= ''

- subnav_actions = []
- if current_admin.email != 'admin2@muddleme.com'
  - subnav_actions << {:controller=>'admins/finance', :action=>'index', :label=>'Finance'}
  - subnav_actions << {:controller=>'admins/auctions', :action=>'index', :label=>'Auctions'}
  - subnav_actions << {:controller=>'admins/users', :action=>'index', :label=>'Customers'}
  - subnav_actions << {:controller=>'admins/vendors', :action=>'index', :label=>'Companies'}
  - subnav_actions << {:controller=>'admins/sales_links', :action=>'index', :label=>'Sales links'}
  - subnav_actions << {:controller=>'admins/box_messages', :action=>'index', :label=>'Search box messages'}
  - subnav_actions << {:controller=>'admins/email_contents', :action=>'index', :label=>'System email messages'}
  - subnav_actions << {:controller=>'admins/withdrawal_requests', :action=>'index', :label=>'WD Requests'}
  - subnav_actions << {:controller=>'admins/affiliated_advertisers', :action=>'index', :label=>'Coupons'}
- else
  - subnav_actions << {:controller=>'admins/affiliated_advertisers', :action=>'index', :label=>'Coupons'}
  - subnav_actions << {:controller=>'admins/affiliated_advertisers', :action=>'affiliates_categories', :label=>'Affiliate links management'}
-# subnav_actions << {:controller=>'admins/stores', :action=>'index', :label=>'Affiliate Stores'}



%ul{:style => "margin-top: -15px; padding: 0px;"}
  - subnav_actions.each do |action|
    - cls = (action[:action]==active_action && action[:controller]==active_controller) ? 'active' : nil
    %li{:class=>cls, :style => 'padding-left: 9px; padding-right: 9px;'}
      = link_to_unless(active_action==action[:action] && action[:controller]==active_controller, action[:label], {:controller=> action[:controller], :action=>action[:action]}) do
        %span= action[:label]
  - if current_admin.email != 'admin2@muddleme.com'
    %ul.mm_dd_menu
      %li
        Affiliates
        %ul.mm_sub_dd_menu
          %li
            = link_to "Links Management", affiliates_categories_admin_affiliated_advertisers_path
          %li
            = link_to "Add Merchants", admin_custom_advertisers_path
          %li
            = link_to "Affiliate Stores", admin_stores_path
          %li
            = link_to "HP Fav Stores", admin_hp_stores_path(:type => "favorite_stores")
          %li
            = link_to "HP Browseable Stores", admin_hp_stores_path(:type => "browseable")
          %li
            = link_to "HP Top Dealers", admin_hp_stores_path(:type => "top_dealers")
      %li
        Categories
        %ul.mm_sub_dd_menu
          %li
            = link_to "Product Category", admins_product_categories_path
          %li
            = link_to "Store Category", admins_store_categories_path
          %li
            = link_to "Add Merchant", admin_add_storecat_to_merchant_index_path
          




:css

  ul.mm_dd_menu {
    text-align: left;
    display: inline-block !important;
    margin: 0;
    padding: 0px 0px 0px 0px;
    color: #797979;
    list-style: none;
    -webkit-box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);
    -moz-box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);
    box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);
  }
  ul.mm_dd_menu li {
  font: bold 12px/18px sans-serif;
  display: inline-block;
  margin-right: -4px;
  position: relative;
  padding: 15px 20px;
  /*background: #fff;*/
  cursor: pointer;
  -webkit-transition: all 0.2s;
    -moz-transition: all 0.2s;
    -ms-transition: all 0.2s;
    -o-transition: all 0.2s;
    transition: all 0.2s;
    }
    ul.mm_dd_menu li:hover {
    background: #555;
    /*color: #fff;*/
    }
    ul.mm_dd_menu li ul.mm_sub_dd_menu {
    padding: 0;
    position: absolute;
    top: 30px;
    left: 0;
    width: 150px;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;
    display: none;
    opacity: 0;
    visibility: hidden;
    -webkit-transiton: opacity 0.2s;
    -moz-transition: opacity 0.2s;
    -ms-transition: opacity 0.2s;
    -o-transition: opacity 0.2s;
    -transition: opacity 0.2s;
    }
    ul.mm_dd_menu li ul.mm_sub_dd_menu li {
      background: #555;
      display: block;
      color: white;
      text-shadow: 0 -1px 0 #000;
      width:100%;
    }

    ul.mm_dd_menu li ul.mm_sub_dd_menu li a{
      color: white !important;
    }

    ul.mm_dd_menu li ul.mm_sub_dd_menu li:hover { background: #666; text-shadow: 0 -1px 0 #797979; color: #797979;}
    ul.mm_dd_menu li ul.mm_sub_dd_menu li a:hover { color: #797979 !important;}
    ul.mm_dd_menu li:hover ul.mm_sub_dd_menu {
      display: block;
      opacity: 1;
      visibility: visible;
    }

my project/app/views/admins/dashboard.html.haml
- content_for :sub_nav do
  = render 'admins/sub_nav', :active_action=>'dashboard', :active_controller=>'/admins'

- content_for :main_column do
  %section.default-content#dashboard
    %article.clearfix

%h2 Admin Dashboard
= render 'layouts/application/one_column'