my project/config/routes.rb
require File.expand_path("../../lib/routes_constraints", __FILE__)


MuddleMe::Application.routes.draw do
  
  namespace :admins do resources :store_categories end
  namespace :admins do resources :product_categories end
   
  # ======== mm box web app routes =============
  get '/google_search' => 'search#google_search', :as => :google_search
  get '/mm_box_search' => 'search#search'
  get '/mm_prompt_cc_window' => 'search#prompt_cc_window'
  post '/hp_mm_box_merchants_search' => 'search#hp_merchants_search'
  get '/hp_pc_merchants' => 'search#hp_pc_merchants'
  get '/hp_mm_box_services_search' => 'search#hp_services_search'
  get '/mm_zip_code_window' => 'search#prompt_zipcode_window'
  get '/mm_box_search_lite' => 'search#search_lite'
  get '/mm_affiliate_merchants_search' => 'search#affiliate_search'
  get '/mm_box_get_current_user' => 'search#get_current_user'
  post '/mm_activate_merchant' => 'search#activate_merchant'
  get '/mm_extension_background_iframe' => 'search#extension_background_iframe'
  get '/mm_box_get_user_messages' => 'search#get_user_messages'
  post '/mm_box_remove_user_message' => 'search#remove_user_message'
  post '/mm_skip_info_before_shopping' => 'search#skip_info_before_shopping'
  get '/mm_check_coupons_by_location' => 'search#check_coupons_by_location'
  get '/muddleme-search' =>'search#muddleme_search'

  # ========= bing search ===================
  get '/bing_search' => 'search#bing_search'

  # utils
  get '/rtest' => 'search#rtest'
  post '/rtest' => 'search#rtest'
  post '/rupload' => 'search#rupload'

  # tmp
  get '/linkshare_mapping' => 'search#linkshare_mapping'
  get '/cj_mapping' => 'search#cj_mapping'
  get '/avant_mapping' => 'search#avant_mapping'
  get '/pj_mapping' => 'search#pj_mapping'
  get '/mm_soleo_number_clicks_report' => 'search#mm_soleo_number_clicks_report'

  # extensions
  get '/mm-extension' => 'application#mm_extension'
  get '/mm-extension-lite' => 'application#mm_extension_lite'
  get '/mm-ie-extension' => 'application#mm_ie_extension'
  get '/mm-firefox-extension' => 'application#mm_firefox_extension'
  get '/mm-chrome-extension' => 'application#mm_chrome_extension'

  get '/safari-extension.safariextz' => 'application#mm_safari_extension'
  get '/safari-extension-lite.safariextz' => 'application#mm_safari_extension_lite'
  get '/safari-extension.plist' => 'application#mm_safari_extension_plist'

  get '/enable-ie' => 'application#enable_ie'
  get '/enable-safari' => 'application#enable_safari'
  get '/search/autocomplete_muddleme_search' => "search#autocomplete_muddleme_search"
  get '/search/autocomplete_service_search' => "search#autocomplete_service_search"

  # ======== mm box web app routes =============
  # ======== backend routes =============
  get '/search_requests' => 'users/search_requests#index', :constraints => LoggedInUserConstraint.new
  get '/search_requests/:id' => 'users/search_requests#show', :constraints => LoggedInUserConstraint.new
  get '/search_requests/:id/outcome' => 'users/search_requests#outcome', :constraints => LoggedInUserConstraint.new
  post '/search_requests/:id/update_outcome' => 'users/search_requests#update_outcome', :constraints => LoggedInUserConstraint.new
  # ======== backend routes =============

  match '/api/auth/facebook/callback' => 'users/api_omniauth_callbacks#facebook'
  match '/api/auth/twitter/callback' => 'users/api_omniauth_callbacks#twitter'
  match '/api/auth/google_oauth2/callback' => 'users/api_omniauth_callbacks#google_oauth2'

  mount Api => "/api"

  root :to => "users#dashboard", :constraints => LoggedInUserConstraint.new
  root :to => "vendors#dashboard", :constraints => LoggedInVendorConstraint.new
  root :to => "admins/finance#index", :constraints => LoggedInAdminConstraint.new

  root :to => 'application#index'
  get '/experience' => 'application#experience'
  get '/referral' => 'application#referral'
  post '/hp_user_sign_up' => 'users#hp_user_sign_up'
  post '/check_subscriber_email' => 'users#check_subscriber_email'
  get '/hp_direct_sign_up' => 'users#hp_direct_sign_up'
  post '/send_sms' => 'users#send_sms_to_users'
  get '/load_more_posts' => 'users#load_more_posts'

  devise_for :users, :controllers => {
    :sessions => "users/devise/sessions",
    :passwords => "users/devise/passwords",
    :registrations => "users/devise/registrations",
    :confirmations => "users/devise/confirmations",
    :unlocks => "users/devise/unlocks",
    :omniauth_callbacks => "users/devise/omniauth_callbacks"
  },
    :skip=>[:sessions, :passwords, :confirmations] do
    get     '/login'   => 'users/devise/sessions#new', :as => "new_user_session"
    post    '/login'   => 'users/devise/sessions#create', :as => "user_session"
    delete  '/logout'  => 'users/devise/sessions#destroy', :as => "destroy_user_session"
    post    '/reset/send'   => 'users/devise/passwords#create', :as => "user_password"
    get     '/reset/send'   => 'users/devise/passwords#new', :as => "new_user_password"
    get     '/reset'        => 'users/devise/passwords#edit', :as => "edit_user_password"
    put     '/reset'        => 'users/devise/passwords#update', :as => "update_user_password"
    get     '/signup'  => 'users/devise/registrations#new', :as => "new_user_registration"
    post    '/signup'  => 'users/devise/registrations#new', :as => "new_user_registration"
    post    '/signup/create'  => 'users/devise/registrations#create', :as => 'user_registration'
    get     '/confirm' => 'users/devise/confirmations#show', :as => "user_confirmation"
    get     '/confirm_new' => 'users/devise/confirmations#new', :as => "new_user_confirmation"
    post    '/confirm' => 'users/devise/confirmations#create', :as => "user_confirmation"
  end

  devise_for :vendors ,
    :controllers => {
    :sessions => "vendors/devise/sessions",
    :passwords => "vendors/devise/passwords",
    :registrations => "vendors/devise/registrations",
    :confirmations => "vendors/devise/confirmations",
    :unlocks => "vendors/devise/unlocks",
  },
    :skip=>[:sessions, :passwords, :confirmations] do
    get     '/company/login'   => 'vendors/devise/sessions#new', :as => "new_vendor_session"
    post    '/company/login'   => 'vendors/devise/sessions#create', :as => "vendor_session"
    delete  '/company/logout'  => 'vendors/devise/sessions#destroy', :as => "destroy_vendor_session"
    post    '/company/reset/send'   => 'vendors/devise/passwords#create', :as => "vendor_password"
    get     '/company/reset/send'   => 'vendors/devise/passwords#new', :as => "new_vendor_password"
    get     '/company/reset'        => 'vendors/devise/passwords#edit', :as => "edit_vendor_password"
    put     '/company/reset'        => 'vendors/devise/passwords#update', :as => "update_vendor_password"
    get     '/company/signup_original'  => 'vendors/devise/registrations#original', :as => "new_vendor_registration"
    get     '/company/signup_premium'  => 'vendors/devise/registrations#premium', :as => "new_vendor_registration"
    get     '/company/signup'  => 'vendors/devise/registrations#new', :as => "new_vendor_registration"
    post    '/company/signup'  => 'vendors/devise/registrations#new', :as => "new_vendor_registration"
    get     '/company/signup/step1'  => 'vendors/devise/registrations#step1', :as => "step1_vendor_registration"
    post    '/company/signup/step1'  => 'vendors/devise/registrations#step1', :as => "step1_vendor_registration"
    get     '/company/signup/step2' => 'vendors/devise/registrations#step2', :as => "step2_vendor_registration"
    post    '/company/signup/step2' => 'vendors/devise/registrations#step2', :as => "step2_vendor_registration"
    post    '/company/signup/create'  => 'vendors/devise/registrations#create', :as => 'vendor_registration'
    get     '/company/confirm' => 'vendors/devise/confirmations#show', :as => "vendor_confirmation"
    get     '/company/confirm_new' => 'vendors/devise/confirmations#new', :as => "new_vendor_confirmation"
    post    '/company/confirm' => 'vendors/devise/confirmations#create', :as => "vendor_confirmation"
  end

  devise_for :admins,
    :controllers => {
    :sessions => "admins/devise/sessions",
    :passwords => "admins/devise/passwords",
  },
    :skip=>[:sessions, :passwords] do
    get     '/admin'   => 'admins/devise/sessions#new', :as => "new_admin_session"
    post    '/admin'   => 'admins/devise/sessions#create', :as => "admin_session"
    delete  '/admin/logout'  => 'admins/devise/sessions#destroy', :as => "destroy_admin_session"
    post    '/admin/reset/send'   => 'admins/devise/passwords#create', :as => "admin_password"
    get     '/admin/reset/send'   => 'admins/devise/passwords#new', :as => "new_admin_password"
    get     '/admin/reset'        => 'admins/devise/passwords#edit', :as => "edit_admin_password"
    put     '/admin/reset'        => 'admins/devise/passwords#update', :as => "update_admin_password"
  end

  match '/contact' => 'contact_messages#new', :as => 'contact', :via => :get
  match '/contact' => 'contact_messages#create', :as => 'contact', :via => :post

  match '/what_is_muddle_me', :to=>'users#what_is_muddle_me'
  match '/what_is_it', :to=>'users#what_is_muddle_me'
  match '/about', :to=>'users#what_is_muddle_me'
  match '/how_it_works', :to=>'users#how_it_works'
  match '/terms_and_conditions', :to => 'users#terms_and_conditions'
  match '/privacy_policy', :to => 'users#privacy_policy'
  match '/faq', :to => 'users#faq'
  match '/UC', :to => 'users#university'
  match '/uc', :to => 'users#university'
  match '/IAC', :to => 'users#iac'
  match '/iac', :to => 'users#iac'


  match "/company", :to => "vendors#dashboard", :as=>'company', :constraints => LoggedInVendorConstraint.new
  match "/company", :to => "vendors#index", :as=>'company'

  match '/company/what_is_muddle_me', :to=>'vendors#what_is_muddle_me'
  match '/company/what_is_it', :to=>'vendors#what_is_muddle_me'
  match '/company/about', :to=>'vendors#what_is_muddle_me'

my project/app/helpers/application_helper.rb
module ApplicationHelper


  def numbered_input form, attribute, simple_form_options={}
    @numbered_input_counters ||= {}
    @numbered_input_counters[form.object_id] ||= 0
    @numbered_input_counters[form.object_id] += 1

    title = strip_tags(form.label(attribute))

    result = "<span class='num' title='#{title}'>#{@numbered_input_counters[form.object_id]}.</span>"
    result += no_label_input(form, attribute, simple_form_options)
    result.html_safe
  end

  def fetch_image_of_advertiser(advertiser, style)
    advertiser.image.exists? ? advertiser.image.url(style.to_sym) : (advertiser.is_a?(LinkshareAdvertiser) ? advertiser.logo_url : advertiser.logo.url)
  end

  def no_label_input  form, attribute, simple_form_options={}
    title = strip_tags(form.label(attribute, :label=>simple_form_options[:label]))
    options = {:input_html=>{:title=>title}}
    options[:label] = false unless simple_form_options[:use_label]

    defaults = {:placeholder=>title}

    form.input attribute, defaults.merge(simple_form_options.deep_merge(options))
  end

  def input_row form, attribute, simple_form_options={}
    return form.input(attribute, simple_form_options) + tag(:hr)
  end

  def inputs_grouped form, attribute, label=nil, hint=nil, required=nil, &block
    content_tag(:div, :class=>"input grouped") do
      content_tag(:div, :class=>'col desc') do
        form.label(attribute, :label=>label, :required=>required) +
          form.hint(hint.blank? ? attribute : hint)
      end + content_tag(:div, :class=>'col flds') do
        yield
      end
    end + tag(:hr)
  end

  def sub_input_row form, attribute, simple_form_options={}
    form.input(attribute, {:wrapper=>:sub_input}.merge(simple_form_options))
  end

  def times_of_day_options
    [['Any time', '']] + $times_of_day.map { |t| [t,t] }
  end

  def seconds_to_time number_of_seconds
    return '' if number_of_seconds.blank?
    hours = (number_of_seconds/3600).to_i
    minutes = (number_of_seconds/60 - hours * 60).to_i
    seconds = (number_of_seconds - (minutes * 60 + hours * 3600))
    sprintf("%02d:%02d:%02d", hours, minutes, seconds)
  end

  def seconds_to_days_and_time number_of_seconds, include_seconds=true
    return '' if number_of_seconds.blank?
    days = number_of_seconds/(3600 * 24)
    hours = (number_of_seconds/3600 - days *  24).to_i
    minutes = (number_of_seconds.to_f/60.0 - (hours * 60 + days * 24 * 60).to_f)
    minutes = include_seconds ? minutes.to_i : minutes.round
    seconds = (number_of_seconds - (minutes * 60 + hours * 3600 + days * (3600 * 24)))
    if include_seconds
      sprintf("%01dd %01dh %01dm %01ds", days, hours, minutes, seconds)
    else
      sprintf("%01dd %01dh %01dm", days, hours, minutes)
    end
  end

  def seconds_to_days_and_time_html number_of_seconds
    return '' if number_of_seconds.blank?
    days = number_of_seconds/(3600 * 24)
    hours = (number_of_seconds/3600 - days *  24).to_i
    minutes = (number_of_seconds/60 - (hours * 60 + days * 24 * 60)).to_i
    seconds = (number_of_seconds - (minutes * 60 + hours * 3600 + days * (3600 * 24)))
    sprintf("<span class='days'>%01d</span>d <span class='hours'>%01d</span>h <span class='minutes'>%01d</span>m <span class='seconds'>%01d</span>s",
      days, hours, minutes, seconds).html_safe
  end

  def paginate *params
    params[1] = {} if params[1].nil?
    params[1][:renderer] = PaginationViewRenderer
    will_paginate *params
  end

  def format_currency value
    number_to_currency(number_with_precision(value, :precision => 2))
  end

  def format_percent_strip value
    number_to_percentage(value, {:precision=>1, :strip_insignificant_zeros=>true})
  end

  def format_datetime value
    value && value.strftime('%m/%d/%Y at %R')
  end

  def format_date value
    value && value.strftime('%m/%d/%Y')
  end

  def url_without_http url
    url.gsub(/https?:\/\//, '')
  end

  def url_with_http url
    http = /https?:\/\//
    if(url.match(http))
      url
    else
      "http://#{url}"
    end
  end

  def trackable_offer_link auction_id, offer
    return '' if offer.offer_url.blank?
    offer_url = url_with_http(offer.trackable_offer_url(auction_id))
    link = create_vendor_tracking_event_path('clicked', :v=>offer.vendor_id, :a=>auction_id,
      :redirect_to=>offer_url)
    link_to offer.offer_url, offer_url, :target=>'_blank', :class=>'trackable-link', :"data-link"=>link
  end

  def list_order_url list_name, param_name
    dir = :ASC
    if instance_variable_get("@#{list_name}_order").to_sym == param_name.to_sym
      dir = instance_variable_get("@#{list_name}_dir").to_sym == :ASC ? :DESC : :ASC
    end
    url_for(params.merge({:"#{list_name}_order" => param_name, :"#{list_name}_dir"=>dir, :"#{list_name}_page"=>nil}))
  end

  def list_order_class list_name, param_name
    ''
    if instance_variable_get("@#{list_name}_order").to_sym == param_name.to_sym
      'active' + if instance_variable_get("@#{list_name}_dir").to_sym == :DESC
        ' up'
      else
        ''
      end
    end
  end

  def credit_card_types
    [
      ["Visa", "visa"], ["MasterCard", "master"],
      ["Discover", "discover"], ["American Express", "american_express"]
    ]
  end

  def facebok_include_sdk
    '<div id="fb-root"></div>' +
      '<script>(function(d, s, id) {'+
      'var js, fjs = d.getElementsByTagName(s)[0];'+
      'if (d.getElementById(id)) return;'+
      'js = d.createElement(s); js.id = id;'+
      "js.src = '//connect.facebook.net/en_US/all.js#xfbml=1&appId=#{SOCIAL_CONFIG['fb_app_id']}';"+
      'fjs.parentNode.insertBefore(js, fjs);'+
      "}(document, 'script', 'facebook-jssdk'));</script>".html_safe
  end

  def facebook_like_button page_url
    '<div class="fb-like" data-href="' + page_url + '" data-send="false"' +
      ' data-layout="button_count" data-width="450" data-show-faces="false"></div>'.html_safe
  end

  def twitter_tweet_button pager_url, text
    '<a href="https://twitter.com/share" class="twitter-share-button" data-url="'+pager_url+'" data-text="' + text + '">Tweet</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>'.html_safe
  end

  def image_tag_unknown_extension(unknown_extension_url)
    extension_code = lambda { |extension|
      url = URI.parse(unknown_extension_url + extension)
      req = Net::HTTP.new(url.host, url.port)
      res = req.request_head(url.path)
      res.code
    }
    jpeg_code = extension_code.call '.jpg'
    if jpeg_code == '404'
      gif_code = extension_code.call '.gif'
      if gif_code == '404'
        png_code = extension_code.call '.png'
        png_code == '404' ? (image_tag 'pixel.gif') : (image_tag unknown_extension_url + '.png')
      else
        image_tag unknown_extension_url + '.gif'
      end
    else
      image_tag unknown_extension_url + '.jpg'
    end
  end

  def get_home_path
    session[:extension_origin].nil? ? google_search_path : session[:extension_origin]
  end

  def check_withdrawal_errors(params)
    params.present? && params == "true"
  end

  def advertiser_coupons(advertiser)
    advertiser.coupons.where(['expires_at IS NULL or expires_at >= ?', Date.today])
  end
end

my project/app/views/application/home_page/_browse_stores_section.html.haml
%section
  .part-4
    .container
      .col-lg-2.col-md-2.col-sm-2.col-xs-2
        %hr/
      .col-lg-8.col-md-8.col-sm-8.col-xs-12.text-center
        %h1 Browse these stores for more great offers and cash back!
      .col-lg-2.col-md-2.col-sm-2.col-xs-2
        %hr/
%section
  .part-5
    .container
      .col-md-12
        #owl-demo.owl-carousel.owl-theme
          - unless @browse_stores.blank?
            - @browse_stores.compact.in_groups_of(4,false) do |group|
              - group.each do |advertiser|
                .item.orange
                  .ribbon
                    %span.ribbontext 
                      = "#{number_to_percentage(advertiser.max_commission_percent, {:precision => 1, :strip_insignificant_zeros => true})} Cash Back"
                  .ms-imgwrapper
                    %img{:alt => "", :src => fetch_image_of_advertiser(advertiser, 'medium'),:title => advertiser.name, :id => "merchant_popup_#{advertiser.advertiser_id}", :class => "img-responsive", :onclick => "generate_popup(this.id, #{advertiser.advertiser_id}, #{advertiser.coupons.blank?}); return false;"}/
                    = link_to "coupon_window", mm_prompt_cc_window_path(:ad => advertiser.advertiser_id, :type => advertiser.class.name, :offer_url => advertiser.advertiser_url), :style => "display:none;", :id => "merchant_c_window_#{advertiser.advertiser_id}"
                    /= "#{advertiser.hp_advertiser_image.nil? ? '$0 off' :  advertiser.hp_advertiser_image.title.blank? ? '$0 off' : advertiser.hp_advertiser_image.title}"








:css
  #right-button {
    width: 0; height: 0;
    border: 20px solid transparent;
    border-left-color: grey;
    cursor: pointer;
  }

  .mar-top-90{
    margin-top: 90px;

  }

  #left-button{
    width: 0; 
    height: 0; 
    border-top: 20px solid transparent;
    border-bottom: 20px solid transparent; 
    border-right:20px solid grey;
    cursor: pointer; 
  }

  .panel-bottom{
    background-color: #F7F7F7;
    padding: 17px;
    font-size: 20px;
    text-align: center;
    bottom: 0;
    position: absolute;
    width: 100%;
  }


:javascript

  $(document).ready(function(){
    var total_images = $(".outer-inner").data("total-count");
    var slide = 1;
    console.log(total_images);
    if(total_images > 3){
        $.each($(".inner"),function(index,value){
            if($(value).data("number") > 2){
                console.log(value)
                $(value).hide();
            }
        });
    }
    
    $("#left-button").click(function(){
        var visible_images = $(".inner:visible").length;
        var first_visible_image = $(".inner:visible").first().data("number");
        if(slide > 1){
            var first_image_range = (first_visible_image  - 3)
            var last_image_range = first_image_range + 3
            $(".inner").hide();
            $.each($(".inner"), function(index, value){
                if($(value).data("number") >= first_image_range && $(value).data("number") < last_image_range){
                    $(value).show();
                }
            });
            slide = slide - 1;
        }
    });
    
    $("#right-button").click(function(){
        var visible_images = $(".inner:visible").length;
        var last_visible_image = $(".inner:visible").last().data("number");
        if(last_visible_image < (total_images -1)){
            var difference = total_images - (last_visible_image + 1)
            if(difference < 4){
                next_images_range = last_visible_image + difference
            }
            else{
                next_images_range = last_visible_image + 3
            }
            $(".inner").hide();
            $.each($(".inner"), function(index, value){
                if($(value).data("number") > last_visible_image && $(value).data("number") <= next_images_range){
                
                    $(value).show();
                }
            })
            slide = slide + 1;
        }
    });

  });

  $(document).ready(function() {

    //Sort random function
    function random(owlSelector){
      owlSelector.children().sort(function(){
          return Math.round(Math.random()) - 0.5;
      }).each(function(){
        $(this).appendTo(owlSelector);
      });
    }

    $("#owl-demo").owlCarousel({
      autoPlay: 3000,
      items: 4
    });

  });

my project/app/views/application/home_page/_coming_soon_popup.html.haml
#coming_soon_popup
  .container-fluid
    .row
      .popup_window
        .coming-soon-container
          %h2 Coming Soon!

my project/app/views/application/home_page/_favorite_stores_section.html.haml
%section
  .part-3.text-center
    .container
      - unless @favorite_stores.blank?
        - @favorite_stores.compact.in_groups_of(3,false) do |group|
          - group.each do |advertiser|
            .col-lg-4.col-md-4.col-sm-4.col-xs-12
              .feture-sec.ms-feature
                %a{:href => "javascript:;"}
                  .ms-info
                    .row
                      .col-xs-12
                        %span{:style => "border: 1px solid white; float: left; width: 70px; background: white none repeat scroll 0% 0%; height: 70px;"}
                          %img.ms-info-img{:alt => "", :src => fetch_image_of_advertiser(advertiser, 'thumb'), :id => "merchant_popup_#{advertiser.advertiser_id}", :class => "img img-responsive fav_merchant",:onclick => "generate_popup(this.id, #{advertiser.advertiser_id}, #{advertiser.coupons.blank?}); return false;"}
                        .ms-info-tx
                          -if advertiser.hp_advertiser_image.blank? or advertiser.hp_advertiser_image.title.blank?
                            %h3= "#{number_to_percentage(advertiser.max_commission_percent, {:precision => 1, :strip_insignificant_zeros => true})} CASH BACK"
                          -else
                            %h3= advertiser.hp_advertiser_image.title

                          %p= "#{advertiser.hp_advertiser_image.blank? ? '' : advertiser.hp_advertiser_image.description}"

                  %a{:href => "javascript:void(0);", :id => "merchant_popup_#{advertiser.advertiser_id}", :class => "img img-responsive fav_merchant", :onclick => "generate_popup(this.id, #{advertiser.advertiser_id}, #{advertiser.coupons.blank?}); return false;"}
                    = image_tag(advertiser.hp_advertiser_image.nil? ? '' : advertiser.is_a?(LinkshareAdvertiser) ? advertiser.hp_advertiser_image.hp_image : advertiser.hp_advertiser_image.hp_image, :title => advertiser.name, :class => "main-img")
                = link_to "coupon_window", mm_prompt_cc_window_path(:ad => advertiser.advertiser_id, :type => advertiser.class.name, :offer_url => advertiser.advertiser_url), :style => "display:none;", :id => "merchant_c_window_#{advertiser.advertiser_id}"

my project/app/views/application/home_page/_popular_categories.html.haml
%section.popular-stories
  .container
    .row
      .col-xs-12
        #all_pc_sections.slidingDiv{:style => "overflow: hidden;"}
          - unless @popular_categories.blank?
            .vertical_listings.popularCat
              - @popular_categories.in_groups_of(5,false) do |group|
                - group.each do |product_cat|
                  %div{:style => "font-size:12px;padding:3px;word-wrap: break-word;"}
                    = link_to product_cat.name, hp_pc_merchants_path(:pcid => product_cat.id), :class => "pcs_list_link"

my project/app/views/application/home_page/_search_by_services_form.html.haml
:css
  .cse-mm-search-bar-icon-wrapper {
    position: relative;
  }

  .cse-search-input-box-id-2 input[type="text"] {
    border: 1px solid #CCC !important;
    width: 585px;
    height: 28px;
    outline: medium none;
    text-indent: 6px;
    font-size: 16px;
    margin-right: -1px;
    padding: 0px !important;
  }
  .cse-mm-search-bar-icon {
    position: absolute;
    right: 10px;
    top: -3px;
  }


%section
  .part-7
    .container
      .col-lg-12.col-md-12.col-sm-12.col-xs-12.text-center
        .square
          = form_tag('#', :id => "sbs_search_bar", :class => "navbar-form") do
            #sbs-form-errors.text-center.text-danger
            = hidden_field_tag :user_id, "#{current_user.id rescue nil}", :class => 'zip-user-id'
            = autocomplete_field_tag 'service_keyword', params[:service_keyword], '/search/autocomplete_service_search', :placeholder => "Electricians, Plumbers, Dish TV....",  :autocomplete => "off", :class => "search rb_regular custom_ss_field"

            - if current_user.present? && !current_user.zip_code.blank?
              = link_to 'SEARCH', "javascript:;", :onClick => "generate_services_search_results_popup();", :id => "sbs_subBtn"
              = link_to "services results", hp_mm_box_services_search_path, :id => "services_results_popup", :style => "display:none;"
            -elsif current_user.present? && current_user.zip_code.blank?
              = link_to 'SEARCH', "javascript:;", :onClick => "generate_zip_code_popup();", :id => "sbs_subBtn"
            -else
              = link_to 'SEARCH', "javascript:;", :onClick => "generate_zip_code_popup();", :id => "sbs_subBtn"
            = link_to "zipcode form", mm_zip_code_window_path, :id => "zip_code_popup", :style => "display:none;"

      .container
        .row
          .col-lg-8.col-md-8.col-lg-offset-2.col-md-offset-2
            .col-lg-4.col-md-4.col-sm-4.col-xs-4.text-center
              .square.align-right
                %h1 Local Merchants
                %img{:alt => "underline", :src => "assets/underline.jpg", :style => "repeat-y; width: 117%;"}
                  %p Direct TV
                  %p Charter communications
                  %p Dish network auth. retailer
            .col-lg-4.col-md-4.col-sm-4.col-xs-4.text-center
              .square.align-center
                %h1{:style => "text-align:center;"} Your Earnings
                %img{:alt => "underline", :src => "assets/underline.jpg", :style => "repeat-y; width: 114%;"}
                  %p $ 12.88
                  %p $ 11.45
                  %p $ 9.74
                  %hr/
                  %p{:style => "font-size:24px;"} $ 34.07
                  %span
                    %p Deposited into your account
            .col-lg-4.col-md-4.col-sm-4.col-xs-4
              .square.text-center.align-left
                %h1{:style => "text-align:center;"} Call Now
                %img{:alt => "underline", :src => "assets/underline.jpg", :style => "repeat-y; width: 100%;"}

                  %p
                    %i.fa.fa-phone
                    View Number
                  %p
                    %i.fa.fa-phone
                    View Number
                  %p
                    %i.fa.fa-phone
                    View Number